# Generated by Django 4.2.7 on 2024-02-11 13:19

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(default="America/Toronto"),
        ),
    ]
