# Generated by Django 4.2.7 on 2023-11-17 21:10

import django.db.models.deletion
from django.db import migrations, models

import groups.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("amount", models.IntegerField()),
                ("payer", models.TextField()),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (groups.models.Expense.Type["EXACT"], "Exact"),
                            (groups.models.Expense.Type["PERCENTAGE"], "Percentage"),
                            (groups.models.Expense.Type["SHARES"], "Shares"),
                            (groups.models.Expense.Type["ADJUSTMENT"], "Adjustment"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("simplify_debts", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseSplit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.TextField()),
                ("shares", models.IntegerField()),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="groups.expense"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="expense",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="groups.expensegroup"
            ),
        ),
        migrations.CreateModel(
            name="ExpenseGroupUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="groups.expensegroup",
                    ),
                ),
            ],
            options={
                "unique_together": {("group", "name")},
            },
        ),
    ]
