# Generated by Django 4.2.7 on 2023-11-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="name",
            field=models.TextField(default="old"),
            preserve_default=False,
        ),
    ]
