# Generated by Django 4.2.7 on 2023-11-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0002_expense_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="is_settle_up",
            field=models.BooleanField(default=False),
        ),
    ]
