# Generated by Django 4.2.7 on 2023-11-19 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0003_expense_is_settle_up"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="expensegroupuser",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="expensegroupuser",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="expense",
            name="payer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="expensesplit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="expensegroupuser",
            unique_together={("group", "user")},
        ),
        migrations.RemoveField(
            model_name="expensegroupuser",
            name="name",
        ),
    ]
