# Generated by Django 4.2.7 on 2023-11-24 00:41

from django.db import migrations, models

import groups.models


def convert_adjustment_to_shares(apps, schema_editor):
    Expense = apps.get_model("groups", "Expense")

    for expense in Expense.objects.filter(type=groups.models.Expense.Type.ADJUSTMENT):
        for split in expense.expensesplit_set.all():
            split.adjustment = split.shares
            split.shares = 1
            split.save(update_fields=["adjustment", "shares"])

        expense.type = groups.models.Expense.Type.SHARES
        expense.save(update_fields=["type"])


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0004_alter_expensegroupuser_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensesplit",
            name="adjustment",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(convert_adjustment_to_shares, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="expense",
            name="type",
            field=models.IntegerField(
                choices=[
                    (groups.models.Expense.Type["EXACT"], "Exact"),
                    (groups.models.Expense.Type["PERCENTAGE"], "Percentage"),
                    (groups.models.Expense.Type["SHARES"], "Shares"),
                ]
            ),
        ),
    ]
