# Generated by Django 4.2.7 on 2024-05-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0006_expensegroupinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=10, default=1, max_digits=20),
        ),
    ]
