# Generated by Django 4.2.7 on 2024-05-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0007_expense_exchange_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="currency_symbol",
            field=models.TextField(default="$"),
        ),
    ]
